### ISSUE TITLE
workflow thoughts / user feedback

### ISSUE THREAD

**Issue by ghost** [vitiral/novault#9]
My workflow expectations have been shaped by [pass](https://www.passwordstore.org/). I don't expect this project to be the same, but figured I'd share some my initial experience using novault.
## design questions
is there a reason the secret is stored separately from the main `novault` directory? 
* Given how many applications on Linux store their configuration, I would suggest putting the `novault.sites` into a `~/.config/novault/`

* I saw the details for setting a PIN, but I often find services make you generate other secrets. I prefer storing these in the password manager. How can I store these secrets alongside the primary site entry?

As a user, I like the workflow of pass more. Caching the password to the system clipboard for a short period of time seems more usable to me than novault's.
How would I store additional secrets within a site? 

## feature requests
1. caching the master password for a time so I don't have to type it in for every password I retrieve
2. create the `novault.sites` on `novault init`, this took me a minute to figure out
3. configurable entropy levels / password length on new entries
   * This is mainly because many companies offering things on the web have terrible password requirements

## random aside / kudos
I noticed there is another [python CLI](https://github.com/novault/) with the same name. Perhaps document the different objective?
I think it is *great* this tool is ~ 1/3 the size of pass

**Comment by vitiral** [comment]
Hey, thanks for the feedback and the suggestions.

1. I've been thinking about adding a looping mechanism similar to my previous tool, litevault. Basically you would use the tool and the password would be good for 2 minutes. After that period, the you could use a shorter password to log into the tool -- but after 3 failed attempts you have to use your full password again.
2. I'm confused, what took you a minute to figure out? You shouldn't normally need to interact directly with `novault.sites` (use `novault set` instead).
3. You can configure the password length using the `--fmt` flag in `novault set`. This also allows you to add whatever characters you want.

I didn't realize the name was taken. I opened an issue letting him know we are the same. Not sure what I'm going to do though since I _really_ like the name! https://github.com/novault/novault/issues/7

**Comment by vitiral** [comment]
Oh, and the reason everything isn't in `.config/novault` is because... I didn't think about that! You are probably right that it should be moved.

When storing multiple secrets I would use you're own convention. I use `mysite.secret1` or whatever.

**Comment by ghost** [comment]
Certainly!
Thanks for the updates.
Ah, using `novault set` makes more sense. For number 2, I didn't realize I needed to run `novault set somesite` to generate the main `novault.sites`. Error on my part. :grinning: 
As for the name, I think it is good too; nice and specific. If you want to be similar I guess you could call this project `norvault` as a nod to the Rust influence.
I opened the issue just to get some thoughts rolling, so feel free to close it or break it up as you see fit.
